services:
  postgres:
    image: postgres:latest
    container_name: arvo-postgres
    environment:
      POSTGRES_USER: arvo
      POSTGRES_PASSWORD: arvo
      POSTGRES_DB: arvo
    ports:
      - "5432:5432"
    volumes:
      - arvo_postgres_data:/var/lib/postgresql

volumes:
  arvo_postgres_data:
